name: Generate Barcode PDF

on:
  push:
    paths:
      - 'uploads/*.xlsx'  # Triggers the action when an Excel file is added to the 'uploads' folder

jobs:
  generate_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas python-barcode reportlab

      - name: Process Excel and Generate PDF
        run: |
          python generate_pdf.py

      - name: Commit PDF
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add output/*.pdf
          git commit -m "Generated barcode PDF"
          git push
