name: Generate Barcode PDF

on:
  push:
    paths:
      - 'uploads/*.xlsx'  # Trigger workflow when an Excel file is added to 'uploads' folder

jobs:
  generate_pdf:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install pandas python-barcode reportlab

      # Step 4: Run the Python script to generate the PDF
      - name: Process Excel and Generate PDF
        run: |
          python generate_pdf.py

      # Step 5: Commit the generated PDF to the output folder
      - name: Commit generated PDF
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add output/*.pdf
          git commit -m "Generated barcode PDF"
          git push
